### ISSUE TITLE
Build platform for iOS 14

### ISSUE THREAD

**Issue by antoinevg** [trigger-corp/forge#44]
## Todo

- [x] Update test devices
- [x] Bump iOS SDK to: `14`
- [x] Bump iOS deployment target version to: `12.4`
- [x] Provision a Xcode 12 build agent on build servers
- [x] Add new simulator device targets

## Test

- [x] Test final deprecation of `AssetsLibrary.framework`  and `assets-library:` URL's
