### ISSUE TITLE
Fix failing tests for module: browsersettings

### ISSUE THREAD

**Issue by antoinevg** [trigger-corp/forge#57]
### TODO

- [ ] Implement support for `NSCrossWebsiteTrackingUsageDescription`

### Failing tests

- [ ] iOS: Looks like _all_ 3rd party cookies are no longer supported under iOS 14.
- [ ] Android: No longer supports parent cookies in iframe.

### More Information

* https://webkit.org/tracking-prevention/
* https://webkit.org/blog/10882/app-bound-domains/
* https://webkit.org/blog/8124/introducing-storage-access-api/
* https://webkit.org/blog/category/privacy/
* https://github.com/apache/cordova-ios/issues/922
* https://github.com/apache/cordova-plugin-inappbrowser/issues/753
* https://stackoverflow.com/questions/61247319/wkwebview-how-to-disable-prevent-cross-site-tracking
* https://bugs.webkit.org/show_bug.cgi?id=188691
* https://bugs.webkit.org/show_bug.cgi?id=140205
* https://developer.apple.com/videos/play/wwdc2020/10188/  23 minutes in
* https://twitter.com/johnwilander/status/1276205640604545025
* https://gist.github.com/chrmod/a5c71f9e7f86782d47eb1734df440260
* https://gist.github.com/iansltx/18caf551baaa60b79206
* https://stackoverflow.com/questions/61543807/safari-iframe-cookie-workaround-in-wkwebview
* https://bugs.webkit.org/show_bug.cgi?id=213510
* https://bugs.webkit.org/show_bug.cgi?id=140205
* https://github.com/oracle/cordova-plugin-wkwebview-file-xhr/blob/master/src/ios/CDVWKWebViewFileXhr.m

**Comment by ice8lue** [comment]
We were in contact with the WebKit team in this thread, where they were looking in direction of a "whitelist": https://bugs.webkit.org/show_bug.cgi?id=213879
